# Generated by Django 6.1 on 2026-09-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilha_ia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicotrilha',
            name='modulo',
        ),
        migrations.RenameField(
            model_name='trilha',
            old_name='generated_at',
            new_name='criado_em',
        ),
        migrations.RenameField(
            model_name='trilha',
            old_name='title',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='trilha',
            name='description',
        ),
        migrations.RemoveField(
            model_name='trilha',
            name='is_active',
        ),
        migrations.AddField(
            model_name='trilha',
            name='conteudo_gerado',
            field=models.JSONField(default={}, help_text='Armazena o JSON completo gerado pela IA contendo os módulos e tópicos.'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ModuloTrilha',
        ),
        migrations.DeleteModel(
            name='TopicoTrilha',
        ),
    ]
