# Generated by Django 6.1 on 2026-10-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilha_ia', '0002_remove_topicotrilha_modulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trilha',
            name='topicos_concluidos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
