# Generated by Django 6.1 on 2026-09-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='privacy',
            field=models.CharField(choices=[('PRIVATE', 'Privado'), ('FRIENDS', 'Amigos'), ('PUBLIC', 'Público')], default='PRIVATE', max_length=20),
        ),
        migrations.AddField(
            model_name='material',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
