# Generated by Django 6.1 on 2026-09-30 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_url', models.URLField(blank=True, help_text='URL para o ícone do selo/badge', null=True)),
                ('xp_required', models.IntegerField(default=0, help_text='XP mínimo para desbloquear')),
                ('is_secret', models.BooleanField(default=False, help_text='Se verdadeiro, não aparece até ser desbloqueado')),
            ],
        ),
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('item_type', models.CharField(choices=[('AVATAR_FRAME', 'Moldura de Avatar'), ('THEME_COLOR', 'Cor de Tema'), ('PROFILE_BADGE', 'Selo de Perfil'), ('PREMIUM_CONTENT', 'Conteúdo Premium')], max_length=20)),
                ('cost_xp', models.IntegerField(help_text='Custo em XP')),
                ('asset_url', models.URLField(blank=True, help_text='URL da imagem ou código do recurso', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Se o usuário está usando isso atualmente')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.storeitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_earned', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
